trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  NODE_VERSION: '22.x'
  IMAGE_NAME: 'auth-service'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: $(NODE_VERSION)

- script: |
    cd auth-services
    npm ci
  displayName: Install dependencies

- script: |
    cd auth-services
    npx prisma generate
  displayName: Generate Prisma Client

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'auth-service'
    cliProjectName: 'auth-service'

- task: SonarQubeAnalyze@7

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  inputs:
    containerRegistry: 'ACR-ServiceConnection'
    repository: 'auth-service'
    command: 'buildAndPush'
    buildContext: 'auth-services'
    Dockerfile: 'auth-services/Dockerfile'
    tags: '$(Build.BuildId)'