trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '22.x'
  IMAGE_NAME: 'subscription-service'

steps:

# Install Node
- task: NodeTool@0
  inputs:
    versionSpec: $(NODE_VERSION)
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    cd subscription-service
    npm ci
  displayName: 'Install dependencies'

# Generate Prisma Client
- script: |
    cd subscription-service
    npx prisma generate
  displayName: 'Generate Prisma Client'

# SonarQube
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'subscription-service'
    cliProjectName: 'subscription-service'

- task: SonarQubeAnalyze@7

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'

# Docker build + push
- task: Docker@2
  inputs:
    containerRegistry: 'ACR-ServiceConnection'
    repository: 'subscription-service'
    command: 'buildAndPush'
    buildContext: 'subscription-service'
    Dockerfile: 'subscription-service/Dockerfile'
    tags: '$(Build.BuildId)'

# Deploy to AKS
- task: KubernetesManifest@1
  inputs:
    action: deploy
    kubernetesServiceConnection: 'AKS-ServiceConnection'
    manifests: |
      k8s/subscription-deployment.yaml